# Modern Docker Compose specification
name: aasdk-builder

services:
  # ARMhf (32-bit ARM) build environment
  build-armhf:
    build:
      context: ../
      dockerfile: buildenv/Dockerfile
      args:
        DEBIAN_RELEASE: trixie
        TARGET_ARCH: armhf
      platforms:
        - linux/arm/v7
    volumes:
      - type: bind
        source: ./release/armhf
        target: /release
        bind:
          create_host_path: true
    environment:
      TARGET_ARCH: armhf
    command: ["/entrypoint.sh", "armhf"]
    profiles:
      - armhf
      - all

  # ARM64 (64-bit ARM) build environment  
  build-arm64:
    build:
      context: ../
      dockerfile: buildenv/Dockerfile
      args:
        DEBIAN_RELEASE: trixie
        TARGET_ARCH: arm64
      platforms:
        - linux/arm64
    volumes:
      - type: bind
        source: ./release/arm64
        target: /release
        bind:
          create_host_path: true
    environment:
      TARGET_ARCH: arm64
    command: ["/entrypoint.sh", "arm64"]
    profiles:
      - arm64
      - all

  # AMD64 (x86_64) build environment
  build-amd64:
    build:
      context: ../
      dockerfile: buildenv/Dockerfile
      args:
        DEBIAN_RELEASE: trixie
        TARGET_ARCH: amd64
      platforms:
        - linux/amd64
    volumes:
      - type: bind
        source: ./release/amd64
        target: /release
        bind:
          create_host_path: true
    environment:
      TARGET_ARCH: amd64
    command: ["/entrypoint.sh", "amd64"]
    profiles:
      - amd64
      - all

  # Development environment for interactive work
  dev:
    build:
      context: ../
      dockerfile: buildenv/Dockerfile
      args:
        DEBIAN_RELEASE: trixie
        TARGET_ARCH: armhf
    volumes:
      - type: bind
        source: ../
        target: /src
        bind:
          create_host_path: true
      - type: bind
        source: ./release/dev
        target: /release
        bind:
          create_host_path: true
    environment:
      TARGET_ARCH: armhf
    command: /bin/bash
    stdin_open: true
    tty: true
    profiles:
      - dev