name: Build and test with docker

on: [ push, pull_request ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t aasdk_builder --file buildenv/Dockerfile .
  compile:    
    runs-on: ${{ matrix.host }}
    needs: [build-image]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        host: [
          "ubuntu-latest",
          #"macos-10.15",
        ]
        config:
          - {
              name: "armhf Release",
              arch: "armhf"
            }
          - {
              name: "amd64 Release",
              arch: "amd64"
            }

    name: 'Upload release:  ${{ matrix.config.name }}'
    steps:
      - 
        name: 'Build ${{ matrix.config.arch }} Debian package'
        run: docker run -v "${PWD}/release":/release aasdk_builder:latest ${{ matrix.config.arch }}