name: Build and test with docker

on: [ push, pull_request ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t aasdk_builder --file Dockerfile .
  compile:	  
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        host: [
          "ubuntu-latest",
          #"macos-10.15",
        ]
        config:
          - {
              name: "armhf Release",
              arch: "armhf",
              type: "release"
            }
          - {
              name: "amd64 Release",
              arch: "amd64",
              type: "release"
            }
	name: 'Upload release:  ${{ matrix.config.name }}'
	steps:
	  - 
	    name: 'Build ${{ matrix.config.arch }} Debian package'
        run: docker run -v "${PWD}/release":/${{ matrix.config.type }} aasdk_builder:latest ${{ matrix.config.arch }}